title: badadumTss codes
email: lucazanny@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Not-so-well writed posts about stuff I do
baseurl: ""
url: ""
twitter_username: luca_zann
github_username:  badadumTss

markdown: kramdown
theme: jekyll-theme-hacker
plugins:
  - jekyll-feed
